import { describe, expect, it } from "vitest";
import {
  getPrusaPresetKey,
  parsePrusaGcodeMetadata,
  parsePrusaTimeToMinutes,
} from "../lib/prusa";

describe("getPrusaPresetKey", () => {
  it("maps supported materials to pinned presets", () => {
    expect(getPrusaPresetKey("PLA")).toBe("pla-default");
    expect(getPrusaPresetKey("PETG")).toBe("petg-default");
  });

  it("falls back to the PLA preset for unknown materials", () => {
    expect(getPrusaPresetKey("ABS")).toBe("pla-default");
  });
});

describe("parsePrusaTimeToMinutes", () => {
  it("parses mixed day/hour/minute/second values", () => {
    expect(parsePrusaTimeToMinutes("1d 2h 30m 0s")).toBe(1590);
    expect(parsePrusaTimeToMinutes("2h 15m 40s")).toBe(136);
  });
});

describe("parsePrusaGcodeMetadata", () => {
  it("extracts filament grams and estimated duration", () => {
    const source = `
; generated by PrusaSlicer
; filament used [g] = 48.57
; estimated printing time (normal mode) = 3h 12m 10s
G28
`;

    expect(parsePrusaGcodeMetadata(source)).toEqual({
      weightGrams: 48.57,
      durationMinutes: 192,
    });
  });
});
